FORMAT: 1A

# Shopping Basket

API allowing merchants to create and maintain a shopping basket holding items their customers might want to purchase.

## All baskets [/baskets]

### Search by customer [GET /baskets?{customer}]

+ Request

    + Headers
    
            Authorization: Basic ABCDEF
            
    + Parameters
    
        + customer (optional, string) ... Customer ID to search by
            
+ Response 200 (application/json)
    
    + Body
    
            [
                { 
                    "basketId": "3849ec7c-6aea-11e6-805a-40a8f045eae5",
                    "createdAt": "2016-08-25T18:31:00Z",
                    "lastUpdated": "2016-08-25T18:31:00Z"
                }
            ]
    

### Create basket [POST]

+ Request (application/json)

    + Headers
    
            Authorization: Basic ABCDEF

    + Body

            {
                "customerId": "someCustomerIdentifier",
                "tags": [
                    "someCustomInformation",
                    "anotherPieceOfInformation"
                ]
            }
    
+ Response 200 (application/json)

    + Headers
    
            Location: /basket/3849ec7c-6aea-11e6-805a-40a8f045eae5
        
    + Body

            {
                "basketId": "3849ec7c-6aea-11e6-805a-40a8f045eae5",
                "createdAt": "2016-08-25T18:31:00Z",
                "lastUpdated": "2016-08-25T18:31:00Z",
            }


## Single basket [/basket/{basketId}]

### View basket [GET]

+ Request

    + Headers
    
            Authorization: Basic ABCDEF

+ Response 200 (application/json)

    + Body
    
            {
                "customerId": "someCustomerIdentifier"
            }

### Discard basket [DELETE]

Remove a basket that is no longer required.

+ Request

    + Headers
        
            Authorization: Basic ABCDEF
            
+ Response 204